/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include  <stdint.h>
#include  <stdio.h>
#include "GPIO_driver_API.h"
#include "SPI_Driver_API.h"

void ADC_ON(void);
uint32_t ADC_Control_Read(uint32_t channel);
void joystickInit(void);

void delay_ms(uint32_t ms);

void spi_Init(void);
void command_to_screen(uint8_t command);
void data_to_screen(uint8_t data);
void SPI_Draw(uint8_t x0, uint8_t x1,uint8_t y0, uint8_t y1, uint16_t color);
void SPI_Set_Cursor(uint8_t x0, uint8_t y0, uint8_t x1, uint8_t y1);
void screen_hardware_reset(void);

int main(void){


		joystickInit();//funkcja zrobiona na API

		spi_Init();

		ADC_ON();

		screen_hardware_reset();
		delay_ms(100);
		command_to_screen(Sleep_Out);
		delay_ms(100);


		command_to_screen(0x3A); //interface pixel format
		data_to_screen(0x05);  // RGB565 16bit pixel format

		//  command_to_screen(0x21); // zmiana orientacji z bialy na czarny
		command_to_screen(Display_On);






	uint8_t button_pressed;





	 while(1){
		 SPI_Draw(50,80, 80, 90,0xF800 );
	//	uint32_t position_x = ADC_Control_Read(0); //nie trzeba czyscic bo samo odczytanie czysci
	//	uint32_t position_y = ADC_Control_Read(1); //nie trzeba czyscic bo samo odczytanie czysci

//		button_pressed = ((GPIO_A->idr>>4) & 0x1) ;
//
		//button_pressed = JoyBtn

//		printf("pozycja z jpysticka: %ld %ld %d \n", position_x, position_y, button_pressed);

		//delay_ms(500);

		//for(volatile int i = 0; i < 500000; i++);

	 }


}





void delay_ms(uint32_t ms) {

    for(uint32_t i = 0; i < (ms * 10000); i++) {
        __asm("nop"); // Pusta instrukcja, żeby kompilator nie usunął pętli
    }
}


void joystickInit(void){

GPIO_PeripheralClockControl(GPIO_A, 1);

//RCC->apb2enr.adc1 = 1;
GPIO_Handle_t JoyX, JoyY, JoyBtn;

JoyX.pGPIO_X_BaseAddr = GPIO_A;
JoyX.GPIO_PinConfig.GPIO_PinNumber = 0; //PA0
JoyX.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Analog; //moder analogowy
GPIO_Init(&JoyX);

JoyY.pGPIO_X_BaseAddr = GPIO_A;
JoyY.GPIO_PinConfig.GPIO_PinNumber = 1; //PA1
JoyY.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Analog; //moder analogowy
GPIO_Init(&JoyY);

JoyBtn.pGPIO_X_BaseAddr = GPIO_A;
JoyBtn.GPIO_PinConfig.GPIO_PinNumber = 4; //PA4
JoyBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Input;
JoyBtn.GPIO_PinConfig.GPIO_PinPullUpPulldownControl = Pull_up;
GPIO_Init(&JoyBtn);

}

void spi_Init(void){
	//zerujemy tak na wszelki
	GPIO_Handle_t DIN = {0};
	GPIO_Handle_t CLK = {0};
	GPIO_Handle_t CS = {0};
	GPIO_Handle_t DC = {0};
	GPIO_Handle_t RST = {0};

	GPIO_PeripheralClockControl(GPIO_C, 1);
	SPI_PeripheralClockControl(SPI3, 1);

	DIN.pGPIO_X_BaseAddr = GPIO_C;
	DIN.GPIO_PinConfig.GPIO_PinNumber = 12;
	DIN.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Alternate;
	DIN.GPIO_PinConfig.GPIO_PinAltFunMode = 6; //spi3
	DIN.GPIO_PinConfig.GPIO_PinSpeed = high_speed;
	GPIO_Init(&DIN);

	CLK.pGPIO_X_BaseAddr = GPIO_C;
	CLK.GPIO_PinConfig.GPIO_PinNumber = 10;
	CLK.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Alternate;
	CLK.GPIO_PinConfig.GPIO_PinAltFunMode = 6; //spi3
	DIN.GPIO_PinConfig.GPIO_PinSpeed = high_speed;
	GPIO_Init(&CLK);

	CS.pGPIO_X_BaseAddr = GPIO_C;
	CS.GPIO_PinConfig.GPIO_PinNumber = 2;
	CS.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Output;
	DIN.GPIO_PinConfig.GPIO_PinSpeed = high_speed;
	GPIO_Init(&CS);

	DC.pGPIO_X_BaseAddr = GPIO_C;
	DC.GPIO_PinConfig.GPIO_PinNumber = 1;
	DC.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Output;
	DIN.GPIO_PinConfig.GPIO_PinSpeed = high_speed;
	GPIO_Init(&DC);

	RST.pGPIO_X_BaseAddr = GPIO_C;
	RST.GPIO_PinConfig.GPIO_PinNumber = 0;
	RST.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Output;
	DIN.GPIO_PinConfig.GPIO_PinSpeed = high_speed;
	GPIO_Init(&RST);

	SPI_Handle_t SPI_3 = {0};

	SPI_3.pSPIx = SPI3;
	SPI_3.SPI_Config.SPI_DeviceMode |= SPI_Master;
	SPI_3.SPI_Config.SPI_BusConfig |=	SPI_BusConfig_fullduplex;
	SPI_3.SPI_Config.SPI_SclkSpeed |= SPI_SCLK_SPEED_div32;
	SPI_3.SPI_Config.SPI_SSM |= SPI_SSM_software;
	SPI_3.SPI_Config.SPI_CPHA |= SPI_CPHA_0;
	SPI_3.SPI_Config.SPI_CPOL|= SPI_CPOL_0;
	SPI_3.SPI_Config.SPI_DFF |= SPI_dff_8bits; //sprawdzic 16
	SPI_Init(&SPI_3);
}
