/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include  <stdint.h>
#include  <stdio.h>
#include "GPIO_driver_API.h"


void ADC_ON(void);
uint32_t ADC_Control_Read(uint32_t channel);

int main(void)

{

	 ADC_ON();

	 uint8_t button_pressed;

	 while(1){
		uint32_t position_x = ADC_Control_Read(0); //nie trzeba czyscic bo samo odczytanie czysci
		uint32_t position_y = ADC_Control_Read(1); //nie trzeba czyscic bo samo odczytanie czysci

		button_pressed = ((GPIO_A->idr>>4) & 0x1) ;


		printf("pozycja z jpysticka: %ld %ld %d \n", position_x, position_y, button_pressed);


		for(volatile int i = 0; i < 500000; i++);

	 }


}

