/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include  <stdint.h>
#include  <stdio.h>
#include "GPIO_driver_API.h"
#include "SPI_Driver_API.h"
#include "object_structure.h"

void ADC_ON(void);
uint32_t ADC_Control_Read(uint32_t channel);
void joystickInit(void);

void delay_ms(uint32_t ms);

void spi_Init(void);
void command_to_screen(uint8_t command);
void data_to_screen(uint8_t data);
void SPI_Draw(uint8_t x0, uint8_t x1,uint8_t y0, uint8_t y1, uint16_t color);
void SPI_Set_Cursor(uint8_t x0, uint8_t y0, uint8_t x1, uint8_t y1);
void screen_hardware_reset(void);
void screen_enable_sequence(void);

void move_jump(uint8_t button, object *pObject);
void move(uint32_t move, object *pObject);

volatile uint8_t button_pressed;
uint8_t gravity = 1;


int main(void){
	uint16_t pos_y0 =10;
	uint16_t pos_y1 =20;

	uint16_t pos_x0 =0;
	uint16_t pos_x1	=20;

	uint8_t jump_debounce= 0;

	uint8_t on_something = 1; // jest na czyms == jest na ziemi == jest na murku

 		joystickInit();//funkcja zrobiona na API

		ADC_ON();

		spi_Init();

		screen_enable_sequence();

		SPI_Draw(0, 129, 0, 160, 0x0000);


		object player, stair;

		player.pos_x0 = pos_x0;
		player.pos_x1 = pos_x1;
		player.pos_y0 = pos_y0;
		player.pos_y1 = pos_y1;

		stair.pos_x0 = 30;
		stair.pos_x1 = 40;
		stair.pos_y0 = 120;
		stair.pos_y1 = 150;

		object_draw(&stair, color_red);
		object_draw(&player, color_green);


	 while(1){
		//uint32_t position_x_adc = ADC_Control_Read(0); //nie trzeba czyscic bo samo odczytanie czysci
		uint32_t position_y_adc = ADC_Control_Read(1); //nie trzeba czyscic bo samo odczytanie czysci
		button_pressed = ((GPIO_A->idr >> 4) & 0x1);

		if(player.pos_x0 != 0 || !on_something){
		object_draw(&player, color_black);
		player.pos_x0 += player.speed;
		player.pos_x1 += player.speed;
		if(player.pos_x0 == 0 && !on_something){
			on_something = 1; // jest na ziemii
					}
		}
		if(!button_pressed && !jump_debounce && on_something){
			object_draw(&player, color_black);
			move_jump(button_pressed, &player);
			jump_debounce =15;
			on_something = 0; // jest w powietrzu
		}
		if(position_y_adc > 2500 || position_y_adc < 1500){
			object_draw(&player, color_black);
			move(position_y_adc, &player);
			}
			object_draw(&player, color_green);
			delay_ms(40);

			//printf("pozycja z jpysticka: %ld %ld %d \n", position_x_adc, position_y_adc, button_pressed);
			 if(jump_debounce>0 && button_pressed){
				 jump_debounce--;
			 }











	 }// }while(1)

}



void delay_ms(uint32_t ms) {

    for(uint32_t i = 0; i < (ms * 1000); i++) {
        __asm("nop"); // Pusta instrukcja, żeby kompilator nie usunął pętli
    }
}


void joystickInit(void){

GPIO_PeripheralClockControl(GPIO_A, 1);

//RCC->apb2enr.adc1 = 1;
GPIO_Handle_t JoyX, JoyY, JoyBtn;

JoyX.pGPIO_X_BaseAddr = GPIO_A;
JoyX.GPIO_PinConfig.GPIO_PinNumber = 0; //PA0
JoyX.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Analog; //moder analogowy
GPIO_Init(&JoyX);

JoyY.pGPIO_X_BaseAddr = GPIO_A;
JoyY.GPIO_PinConfig.GPIO_PinNumber = 1; //PA1
JoyY.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Analog; //moder analogowy
GPIO_Init(&JoyY);

JoyBtn.pGPIO_X_BaseAddr = GPIO_A;
JoyBtn.GPIO_PinConfig.GPIO_PinNumber = 4; //PA4
JoyBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Input;
JoyBtn.GPIO_PinConfig.GPIO_PinPullUpPulldownControl = Pull_up;
GPIO_Init(&JoyBtn);
}

void spi_Init(void){
	//zerujemy tak na wszelki
	GPIO_Handle_t DIN = {0};
	GPIO_Handle_t CLK = {0};
	GPIO_Handle_t CS = {0};
	GPIO_Handle_t DC = {0};
	GPIO_Handle_t RST = {0};

	GPIO_PeripheralClockControl(GPIO_C, 1);
	SPI_PeripheralClockControl(SPI3, 1);

	DIN.pGPIO_X_BaseAddr = GPIO_C;
	DIN.GPIO_PinConfig.GPIO_PinNumber = 12;
	DIN.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Alternate;
	DIN.GPIO_PinConfig.GPIO_PinAltFunMode = 6; //spi3
	DIN.GPIO_PinConfig.GPIO_PinSpeed = high_speed;
	GPIO_Init(&DIN);

	CLK.pGPIO_X_BaseAddr = GPIO_C;
	CLK.GPIO_PinConfig.GPIO_PinNumber = 10;
	CLK.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Alternate;
	CLK.GPIO_PinConfig.GPIO_PinAltFunMode = 6; //spi3
	DIN.GPIO_PinConfig.GPIO_PinSpeed = high_speed;
	GPIO_Init(&CLK);

	CS.pGPIO_X_BaseAddr = GPIO_C;
	CS.GPIO_PinConfig.GPIO_PinNumber = 2;
	CS.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Output;
	DIN.GPIO_PinConfig.GPIO_PinSpeed = high_speed;
	GPIO_Init(&CS);

	DC.pGPIO_X_BaseAddr = GPIO_C;
	DC.GPIO_PinConfig.GPIO_PinNumber = 1;
	DC.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Output;
	DIN.GPIO_PinConfig.GPIO_PinSpeed = high_speed;
	GPIO_Init(&DC);

	RST.pGPIO_X_BaseAddr = GPIO_C;
	RST.GPIO_PinConfig.GPIO_PinNumber = 0;
	RST.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_Output;
	DIN.GPIO_PinConfig.GPIO_PinSpeed = high_speed;
	GPIO_Init(&RST);

	SPI_Handle_t SPI_3 = {0};

	SPI_3.pSPIx = SPI3;
	SPI_3.SPI_Config.SPI_DeviceMode |= SPI_Master;
	SPI_3.SPI_Config.SPI_BusConfig |=	SPI_BusConfig_fullduplex;
	SPI_3.SPI_Config.SPI_SclkSpeed |= SPI_SCLK_SPEED_div4;
	SPI_3.SPI_Config.SPI_SSM |= SPI_SSM_software;
	SPI_3.SPI_Config.SPI_CPHA |= SPI_CPHA_0;
	SPI_3.SPI_Config.SPI_CPOL|= SPI_CPOL_0;
	SPI_3.SPI_Config.SPI_DFF |= SPI_dff_8bits; //sprawdzic 16
	SPI_Init(&SPI_3);
}

	void screen_enable_sequence(void){
		screen_hardware_reset();
		delay_ms(50);
		command_to_screen(0x01); //software reset
		delay_ms(50);
		command_to_screen(Sleep_Out);
		delay_ms(50);


		command_to_screen(0x3A); //interface pixel format
		data_to_screen(0x05);  // RGB565 16bit pixel format

		//  command_to_screen(0x21); // zmiana orientacji z bialy na czarny
		command_to_screen(Display_On);


	}

